# Generated by Django 3.0.3 on 2020-10-18 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instrument', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='section_name',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name', to='Instrument.Section'),
        ),
    ]
