# Generated by Django 3.0.3 on 2020-10-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrument', '0003_auto_20201018_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='photo_file_name',
        ),
        migrations.AddField(
            model_name='instrument',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
