# Generated by Django 3.0.3 on 2020-10-18 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instrument', '0004_auto_20201018_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrument', to='Instrument.Section'),
        ),
    ]
