# Generated by Django 3.0.3 on 2020-10-19 09:34

import Instrument.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instrument', '0006_auto_20201018_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(null=True, upload_to=Instrument.models.instrument_image_file_path),
        ),
    ]
